version: '3.8'

services:
  clippilot_backend:
    build:
      context: . # Specifies the build context is the current directory (where Dockerfile is)
      dockerfile: Dockerfile # Specifies the name of the Dockerfile
    container_name: clippilot_backend_service
    restart: unless-stopped # Restarts the container unless it was explicitly stopped
    ports:
      - "8001:8001" # Maps port 8001 on the host to port 8001 in the container
    volumes:
      # Named volume for ChromaDB data persistence
      - chroma_data:/app/data/chroma_db_dev
      # Named volume for temporary video processing uploads (persists them if needed for debugging)
      - temp_uploads_data:/app/temp_uploads
      # --- For Development: Mount source code for live reload (optional) ---
      # Uncomment these lines if you want changes in your local code to reflect
      # immediately in the running container. Note: Uvicorn's --reload would also be needed.
      # This is generally not for production images.
      # - ./main.py:/app/main.py
      # - ./services:/app/services
    env_file:
      - .env # Loads environment variables from a .env file in the same directory
    environment:
      # You can override or set additional environment variables here if needed
      # These take precedence over those in the .env file for the container.
      # Example:
      # - PYTHONUNBUFFERED=1 # Already in Dockerfile, but can be set here too
      - TEMP_VIDEO_DIR=/app/temp_uploads # Ensures container path is used
      - CHROMA_DB_PATH=/app/data/chroma_db_dev # Ensures container path is used

volumes:
  chroma_data: # Defines a named Docker volume for ChromaDB
    driver: local # Uses the local driver, meaning data is stored on the Docker host
  temp_uploads_data: # Defines a named Docker volume for temporary uploads
    driver: local